Fixed problem with fotter component typo. Added classroom types list admin page.
SilverNETGroupSGGW/Sopelek pull request #50
Opened 2024-05-02 15:53 UTC by FabianoIV

2024-05-02 17:27 UTC, Mensix requested changes

2024-05-02 17:27 UTC, Mensix commented on components/layout/footer.vue
> +<script setup lang="ts">
Bez tego

2024-05-02 17:27 UTC, Mensix commented on pages/tenant-administration/classroom-types.vue
> +      <input
A niżej używasz komponentu base-checkbox

2024-05-02 17:27 UTC, Mensix commented on pages/tenant-administration/classroom-types.vue
> +      <base-checkbox v-model="cell.isPrimitiveType" label="" :disabled="true" />
Jeśli label może być pusty, to niech jego typ to będzie ```string?```

2024-05-02 17:27 UTC, Mensix commented on pages/tenant-administration/classroom-types.vue
> +      <base-checkbox v-model="cell.isPrimitiveType" label="" :disabled="true" />
Poza tym, domyślnie binduje się true jeżeli booleanowy prop jest obecny
```suggestion
      <base-checkbox v-model="cell.isPrimitiveType" />
```

2024-05-02 17:27 UTC, Mensix commented on pages/tenant-administration/index.vue
> +                to="/tenant-administration/classroom-types"
Bez ```to```

2024-05-05 14:51 UTC, FabianoIV commented on pages/tenant-administration/classroom-types.vue
> +      <input
Ta zmiana do refactoru w innym branchu

2024-05-05 15:05 UTC, FabianoIV commented on pages/tenant-administration/classroom-types.vue
> +      <base-checkbox v-model="cell.isPrimitiveType" label="" :disabled="true" />
Co do diasbled to domyślnie jest false, sprawdziłem. label usuwam.

2024-05-05 15:07 UTC, FabianoIV commented on pages/tenant-administration/classroom-types.vue
> +      <base-checkbox v-model="cell.isPrimitiveType" label="" :disabled="true" />
Domyślnie wszystkie zmienne boolowskie mają false. Bo kiedyś w C wartość bół powstała z wartości int, gdzie 0 to false, a dowolna inna wartośc to 1. A domyślnie nieprzypisany int ma 0.

I taki standard jest.

2024-05-05 15:10 UTC, FabianoIV commented on pages/tenant-administration/index.vue
> +                to="/tenant-administration/classroom-types"
Usunięte

2024-05-05 15:14 UTC, Mensix approved these changes

2024-05-05 15:14 UTC, Mensix commented on pages/tenant-administration/classroom-types.vue
>      </template>
Starczy disabled po prostu

2024-05-06 08:03 UTC, merged