Add free days calendar page
SilverNETGroupSGGW/Sopelek pull request #55
Opened 2024-05-18 23:32 UTC by FabianoIV

2024-05-19 20:18 UTC, Mensix requested changes

2024-05-19 20:18 UTC, Mensix commented on components/base/calendar.vue
> +const reset = function () {
```suggestion
function reset() {
```

2024-05-19 20:18 UTC, Mensix commented on components/base/calendar.vue
> +const shiftMonth = function (amount: number) {
```suggestion
function shiftMonth(amount: number) {
```

2024-05-19 20:18 UTC, Mensix commented on components/base/calendar.vue
> +  startDate?: '2022-12-05'
?

2024-05-19 20:18 UTC, Mensix commented on components/base/calendar.vue
> +    ranges.push(currentDate)
No wtedy to powinna być funkcja jak już zamiast computed

2024-05-19 20:18 UTC, Mensix commented on components/base/calendar.vue
> +const daysToPrepend = computed(() => {
Jak niżej

```suggestion
function daysToPrepend() {
```

2024-05-19 20:18 UTC, Mensix commented on components/base/calendar.vue
> +      <div v-for="p in daysToPrepend" :key="p.toString()" class="bg-midnight" />
```suggestion
      <div v-for="p in daysToPrepend" :key="p.toString()" class="bg-gray-900" />
```

2024-05-19 20:18 UTC, Mensix commented on components/base/popover.vue
Do o

2024-05-19 20:18 UTC, Mensix commented on pages/free-days-calendar.vue
> +            <div v-for="offDay in offDays.data.filter(od => isEqual(new Date(od.date), date))" :key="offDay.id">
Taki skomplikowane coś to bym wrzucił do oddzielnego computeda

2024-05-19 20:18 UTC, Mensix commented on pages/free-days-calendar.vue
> +      <base-input v-if="currentItem.scope === 'Tenant'" v-model="currentItem.tenantId" :icon="IconUser" label="Id Tenantu" />
v-else-if

2024-05-19 20:18 UTC, Mensix commented on pages/free-days-calendar.vue
> +      <base-input v-if="currentItem.scope === 'Schedule'" v-model="currentItem.scheduleId" :icon="IconUser" label="Id Planu Zajęć" />
v-else-if

2024-05-19 20:18 UTC, Mensix commented on pages/free-days-calendar.vue
> +      <base-input v-if="currentItem.scope === 'Group'" v-model="currentItem.groupId" :icon="IconUser" label="Id Grupy" />
v-else-if / v-else

2024-05-19 20:18 UTC, Mensix commented on pages/free-days-calendar.vue
> +      <base-input v-if="currentItem.scope === 'Tenant'" v-model="currentItem.tenantId" :icon="IconUser" label="Id Tenantu" />
jw

2024-05-20 08:13 UTC, FabianoIV commented on components/base/calendar.vue
> +  startDate?: '2022-12-05'
A racja, miałem zrobić w kontrolce inne widoki

2024-05-20 08:14 UTC, FabianoIV commented on components/base/calendar.vue
> +const shiftMonth = function (amount: number) {
Zmieniam

2024-05-22 22:43 UTC, FabianoIV commented on components/base/calendar.vue
> +    ranges.push(currentDate)
Zmienię, ale to akurat z template rozwiązanie jest.
W sensie computed było w template.

2024-05-23 11:53 UTC, Mensix approved these changes

2024-05-23 12:19 UTC, merged